language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  code_climate:
    repo_token: 6c629c2a08ad12f96fa4d840f42ed19ce33fdbfd4a85b9f7260d4df47d648825

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - phpunit
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v